"""
Static catalog of common U.S. consumer credit cards for educational matching.
Not affiliated with issuers; typical score bands are rough public guidance only.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


@dataclass(frozen=True)
class CardSpec:
    id: str
    name: str
    issuer: str
    category: Literal["secured", "student", "cash_back", "travel", "premium_travel", "charge", "store", "flat_rewards"]
    annual_fee_usd: int
    score_typical_min: int
    score_typical_max: int
    income_comfortable_min: int | None  # annual USD; below = fee harder to justify
    pros: tuple[str, ...]
    cons: tuple[str, ...]
    avoid_if: tuple[str, ...]  # human-readable rules for "skip" messaging


CARDS: tuple[CardSpec, ...] = (
    CardSpec(
        id="discover_secured",
        name="Discover it® Secured",
        issuer="Discover",
        category="secured",
        annual_fee_usd=0,
        score_typical_min=300,
        score_typical_max=639,
        income_comfortable_min=None,
        pros=(
            "No annual fee; common path to graduate to unsecured.",
            "Cash-back categories may help rewards while building credit.",
        ),
        cons=(
            "Requires a refundable security deposit.",
            "Not useful if you already qualify for strong unsecured cards.",
        ),
        avoid_if=("You already have good/excellent credit and want premium perks.",),
    ),
    CardSpec(
        id="cap1_platinum_secured",
        name="Capital One Platinum Secured",
        issuer="Capital One",
        category="secured",
        annual_fee_usd=0,
        score_typical_min=300,
        score_typical_max=639,
        income_comfortable_min=None,
        pros=("No annual fee; may offer a path to a higher line after responsible use.",),
        cons=("Security deposit required; rewards are limited vs unsecured cash-back cards.",),
        avoid_if=("You qualify for unsecured rewards cards with similar or no fee.",),
    ),
    CardSpec(
        id="opensky_secured",
        name="OpenSky® Secured Visa®",
        issuer="Capital Bank N.A.",
        category="secured",
        annual_fee_usd=35,
        score_typical_min=300,
        score_typical_max=620,
        income_comfortable_min=None,
        pros=("May work when other issuers decline; no bank account required in some cases.",),
        cons=("Annual fee; generally weaker long-term value than no-fee secured options.",),
        avoid_if=("You can qualify for a no-annual-fee secured card instead.",),
    ),
    CardSpec(
        id="discover_student",
        name="Discover it® Student Cash Back",
        issuer="Discover",
        category="student",
        annual_fee_usd=0,
        score_typical_min=580,
        score_typical_max=720,
        income_comfortable_min=None,
        pros=("No annual fee; rotating bonus categories; Good Grade Reward on some versions.",),
        cons=("Rotating categories require activation; less travel transfer value than Chase/Amex ecosystems.",),
        avoid_if=("You are not a student and have stronger profiles—other cards may fit better.",),
    ),
    CardSpec(
        id="journey_student",
        name="Capital One Journey Student Rewards",
        issuer="Capital One",
        category="student",
        annual_fee_usd=0,
        score_typical_min=580,
        score_typical_max=700,
        income_comfortable_min=None,
        pros=("Simple cash-back structure; no foreign transaction fees on many Capital One cards.",),
        cons=("Rewards rate may be modest unless you qualify for tiered bonuses.",),
        avoid_if=("You are not a student.",),
    ),
    CardSpec(
        id="cfcu",
        name="Citi® Double Cash",
        issuer="Citi",
        category="cash_back",
        annual_fee_usd=0,
        score_typical_min=670,
        score_typical_max=850,
        income_comfortable_min=35_000,
        pros=("Straightforward 2% total cash-back story when paid in full (structure varies by product rules).",),
        cons=("Less travel upside than transferable-points cards unless you pair with premium Citi products.",),
        avoid_if=("You want maximum travel transfer partners and lounge perks from one card.",),
    ),
    CardSpec(
        id="cfu",
        name="Chase Freedom Unlimited®",
        issuer="Chase",
        category="cash_back",
        annual_fee_usd=0,
        score_typical_min=680,
        score_typical_max=850,
        income_comfortable_min=40_000,
        pros=("Pairs well with Chase Sapphire cards for points transfers; simple baseline earning.",),
        cons=("Best value often assumes you also hold a Sapphire-family card.",),
        avoid_if=("You are over 5/24 with Chase and cannot get approved under Chase rules.",),
    ),
    CardSpec(
        id="cflex",
        name="Chase Freedom Flex℠",
        issuer="Chase",
        category="cash_back",
        annual_fee_usd=0,
        score_typical_min=680,
        score_typical_max=850,
        income_comfortable_min=40_000,
        pros=("Rotating 5% categories; good complement to a Sapphire strategy.",),
        cons=("Requires category activation; Chase approval rules can be strict.",),
        avoid_if=("You cannot manage rotating categories or are blocked by 5/24.",),
    ),
    CardSpec(
        id="bce",
        name="Blue Cash Everyday® from American Express",
        issuer="American Express",
        category="cash_back",
        annual_fee_usd=0,
        score_typical_min=670,
        score_typical_max=850,
        income_comfortable_min=35_000,
        pros=("No annual fee; useful U.S. supermarket/streaming category angles for many households.",),
        cons=("Amex acceptance is not universal internationally vs Visa/Mastercard.",),
        avoid_if=("You need maximum international merchant coverage on one physical network.",),
    ),
    CardSpec(
        id="bcp",
        name="Blue Cash Preferred® from American Express",
        issuer="American Express",
        category="cash_back",
        annual_fee_usd=95,
        score_typical_min=680,
        score_typical_max=850,
        income_comfortable_min=50_000,
        pros=("Strong grocery/streaming cash-back rates if your spend matches the categories.",),
        cons=("Annual fee—must run a break-even vs Everyday based on real spend.",),
        avoid_if=("Your grocery spend is low or you dislike annual fees.",),
    ),
    CardSpec(
        id="apple_card",
        name="Apple Card",
        issuer="Goldman Sachs / Apple",
        category="store",
        annual_fee_usd=0,
        score_typical_min=660,
        score_typical_max=850,
        income_comfortable_min=None,
        pros=("Clean app experience; Daily Cash; no fees in many common cases.",),
        cons=("Ecosystem tie-in; underwriting and issuer situation has changed over time—verify current terms.",),
        avoid_if=("You do not use Apple devices or prefer a traditional issuer relationship.",),
    ),
    CardSpec(
        id="venture",
        name="Capital One Venture Rewards",
        issuer="Capital One",
        category="travel",
        annual_fee_usd=95,
        score_typical_min=690,
        score_typical_max=850,
        income_comfortable_min=55_000,
        pros=("Simple miles earning; decent travel protections for a mid-tier fee.",),
        cons=("Transfer partners differ from Chase/Amex; evaluate partner fit.",),
        avoid_if=("You will not use travel redemptions enough to offset the annual fee.",),
    ),
    CardSpec(
        id="venture_x",
        name="Capital One Venture X®",
        issuer="Capital One",
        category="premium_travel",
        annual_fee_usd=395,
        score_typical_min=720,
        score_typical_max=850,
        income_comfortable_min=90_000,
        pros=("Premium travel credits/lounge access if you use included benefits.",),
        cons=("High annual fee; requires intentional use of perks to break even.",),
        avoid_if=("Low income, low travel spend, or you dislike optimizing credits.",),
    ),
    CardSpec(
        id="csp",
        name="Chase Sapphire Preferred®",
        issuer="Chase",
        category="travel",
        annual_fee_usd=95,
        score_typical_min=690,
        score_typical_max=850,
        income_comfortable_min=55_000,
        pros=("Strong transferable points; broad travel/dining category fit for many users.",),
        cons=("Annual fee; Chase 5/24 and other internal rules can block approvals.",),
        avoid_if=("You are unlikely to pass 5/24 or you will not use points for travel/dining.",),
    ),
    CardSpec(
        id="csr",
        name="Chase Sapphire Reserve®",
        issuer="Chase",
        category="premium_travel",
        annual_fee_usd=550,
        score_typical_min=720,
        score_typical_max=850,
        income_comfortable_min=100_000,
        pros=("Premium travel credits and lounge access if your travel pattern matches.",),
        cons=("Very high annual fee; benefits change over time—verify current credits.",),
        avoid_if=("You travel rarely or cannot justify the fee with credits plus points value.",),
    ),
    CardSpec(
        id="amex_gold",
        name="American Express® Gold Card",
        issuer="American Express",
        category="charge",
        annual_fee_usd=325,
        score_typical_min=670,
        score_typical_max=850,
        income_comfortable_min=60_000,
        pros=("Strong dining/grocery multipliers for many urban households.",),
        cons=("Charge card—typically pay in full; high annual fee.",),
        avoid_if=("You need to carry a balance or your dining/grocery spend is low.",),
    ),
    CardSpec(
        id="amex_platinum",
        name="The Platinum Card® from American Express",
        issuer="American Express",
        category="premium_travel",
        annual_fee_usd=695,
        score_typical_min=700,
        score_typical_max=850,
        income_comfortable_min=120_000,
        pros=("Lounges and premium travel credits can be huge if you already spend that way.",),
        cons=("Very high fee; many benefits require enrollment and usage discipline.",),
        avoid_if=("You do not fly often or will not use lounge/credit stack.",),
    ),
    CardSpec(
        id="united_quest",
        name="United Quest℠ Card",
        issuer="Chase",
        category="travel",
        annual_fee_usd=350,
        score_typical_min=700,
        score_typical_max=850,
        income_comfortable_min=80_000,
        pros=("MileagePlus perks if United is your primary airline.",),
        cons=("Airline cobrand value depends on hub/route fit; annual fee.",),
        avoid_if=("You rarely fly United or are not loyal to Star Alliance via United.",),
    ),
    CardSpec(
        id="delta_gold",
        name="Delta SkyMiles® Gold American Express Card",
        issuer="American Express",
        category="travel",
        annual_fee_usd=150,
        score_typical_min=680,
        score_typical_max=850,
        income_comfortable_min=50_000,
        pros=("Checked bag and boarding perks can save money if you fly Delta often.",),
        cons=("Value is tied to Delta; annual fee after the first year in many offers.",),
        avoid_if=("You do not fly Delta or already get bags/fees waived another way.",),
    ),
    CardSpec(
        id="wf_active",
        name="Wells Fargo Active Cash®",
        issuer="Wells Fargo",
        category="flat_rewards",
        annual_fee_usd=0,
        score_typical_min=670,
        score_typical_max=850,
        income_comfortable_min=35_000,
        pros=("Simple flat cash-back on purchases for many users.",),
        cons=("Less ecosystem upside than Chase/Amex points strategies.",),
        avoid_if=("You want transferable points and premium travel partners only.",),
    ),
    CardSpec(
        id="boa_custom",
        name="Bank of America® Customized Cash Rewards",
        issuer="Bank of America",
        category="cash_back",
        annual_fee_usd=0,
        score_typical_min=670,
        score_typical_max=850,
        income_comfortable_min=35_000,
        pros=("Pick-your-category cash-back; better with Preferred Rewards banking tiers.",),
        cons=("Best rates often assume banking relationship; caps on bonus categories.",),
        avoid_if=("You will not use BoA/Merrill relationship tiers and dislike caps.",),
    ),
)
